import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
// import "@uploadthing/react/styles.css";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs';
import { ToastProvider } from "@/providers/toaster-provider";
import { ConfettiProvider } from "@/providers/confetti-provider";
const inter = Inter({ subsets: ['latin'] })



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body className={inter.className}>
        <ConfettiProvider />
        <ToastProvider />
        {children}
      </body>
    </html>
    </ClerkProvider>
    
  )
}
